server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    add_header Access-Control-Allow-Origin * always;
    add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Content-Type, Range" always;
    add_header Access-Control-Expose-Headers "Content-Length, Content-Range, Accept-Ranges" always;

    location / {
        try_files $uri =404;
    }
}